import React, { createContext, useContext, useState, useEffect } from 'react';
// AsyncStorage removed - using Supabase only

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const LANGUAGES = {
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
  },
  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
  },
  fr: {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
  },
  de: {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪',
  },
  it: {
    code: 'it',
    name: 'Italiano',
    flag: '🇮🇹',
  },
  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇵🇹',
  },
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
  },
  ja: {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
  },
  ko: {
    code: 'ko',
    name: '한국어',
    flag: '🇰🇷',
  },
  ar: {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
  },
};

const TRANSLATIONS = {
  en: {
    // Common
    home: 'Home',
    explore: 'Explore',
    messages: 'Messages',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    done: 'Done',
    close: 'Close',
    open: 'Open',
    select: 'Select',
    submit: 'Submit',
    confirm: 'Confirm',
    continue: 'Continue',
    
    // Navigation
    dashboard: 'Dashboard',
    jobs: 'Jobs',
    findJobs: 'Find Jobs',
    activeJobs: 'Active Jobs',
    jobHistory: 'Job History',
    bidding: 'Bidding',
    myBookings: 'My Bookings',
    bookService: 'Book Service',
    
    // Home Screen
    goodMorning: 'Good Morning!',
    goodAfternoon: 'Good Afternoon!',
    goodEvening: 'Good Evening!',
    beProductiveToday: 'Be Productive Today!',
    quickActions: 'Quick Actions',
    createJob: 'Create Job',
    postNewServiceRequest: 'Post a new service request',
    myJobs: 'My Jobs',
    manageYourRequests: 'Manage your requests',
    chatWithMechanics: 'Chat with mechanics',
    carDetails: 'Car Details',
    manageYourVehicles: 'Manage your vehicles',
    activeProjects: 'Active Projects',
    viewAll: 'View All',
    scheduledServices: 'Scheduled Services',
    availableMechanics: 'Available Mechanics',
    
    // Explore Screen
    findPerfectMechanic: 'Find the perfect mechanic for your needs',
    searchMechanicsOrSpecialties: 'Search mechanics or specialties...',
    categories: 'Categories',
    languages: 'Languages',
    noMechanicsFound: 'No mechanics found matching your criteria',
    contact: 'Contact',
    yearsExp: 'years exp.',
    languagesSpoken: 'Languages:',
    
    // Profile Screen
    customer: 'Customer',
    mechanic: 'Mechanic',
    editProfile: 'Edit Profile',
    preferences: 'Preferences',
    notifications: 'Notifications',
    privacy: 'Privacy',
    help: 'Help',
    about: 'About',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    userInfo: 'User Information',
    professionalStats: 'Professional Stats',
    completedJobs: 'Completed Jobs',
    totalJobs: 'Total Jobs',
    specialties: 'Specialties',
    expertise: 'Expertise',
    personalStatement: 'Personal Statement',
    hourlyRate: 'Hourly Rate',
    
    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    easyLogin: 'Easy Login',
    customerLogin: 'Customer Login',
    mechanicLogin: 'Mechanic Login',
    selectUserType: 'Select User Type',
    
    // Job related
    createNewJob: 'Create New Job',
    jobTitle: 'Job Title',
    jobDescription: 'Job Description',
    serviceType: 'Service Type',
    urgency: 'Urgency',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    estimatedDuration: 'Estimated Duration',
    budget: 'Budget',
    location: 'Location',
    carInformation: 'Car Information',
    addCarDetails: 'Add Car Details',
    helpMechanicsWithBetterDiagnostics: 'Help mechanics with better diagnostics',
    jobManagement: 'Job Management',
    jobStatus: 'Job Status',
    inProgress: 'In Progress',
    completed: 'Completed',
    cancelled: 'Cancelled',
    requirements: 'Requirements',
    acceptedBid: 'Accepted Bid',
    
    // Car Info
    carMake: 'Car Make',
    carModel: 'Car Model',
    carYear: 'Car Year',
    carColor: 'Car Color',
    licensePlate: 'License Plate',
    vinNumber: 'VIN Number',
    mileage: 'Mileage',
    lastServiceDate: 'Last Service Date',
    serviceHistory: 'Service History',
    vehicleDetails: 'Vehicle Details',
    addVehicle: 'Add Vehicle',
    updateVehicle: 'Update Vehicle',
    
    // Messaging
    sendMessage: 'Send Message',
    typeMessage: 'Type a message...',
    newMessage: 'New Message',
    messageHistory: 'Message History',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Last seen',
    
    // Bidding
    submitBid: 'Submit Bid',
    bidAmount: 'Bid Amount',
    estimatedTime: 'Estimated Time',
    bidMessage: 'Message',
    availableDate: 'Available Date',
    bidSubmitted: 'Bid Submitted',
    bidAccepted: 'Bid Accepted',
    bidRejected: 'Bid Rejected',
    
    // Reviews
    rateMechanic: 'Rate Mechanic',
    rateYourExperience: 'Rate Your Experience',
    overallRating: 'Overall Rating',
    quality: 'Quality',
    timeliness: 'Timeliness',
    communication: 'Communication',
    cleanliness: 'Cleanliness',
    writeReview: 'Write Review',
    submitReview: 'Submit Review',
    reviewSubmitted: 'Review Submitted',
    
    // Scheduling
    scheduleAppointment: 'Schedule Appointment',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    appointmentBooked: 'Appointment Booked',
    reschedule: 'Reschedule',
    cancelAppointment: 'Cancel Appointment',
    
    // Payment
    payment: 'Payment',
    paymentMethod: 'Payment Method',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cardholderName: 'Cardholder Name',
    processPayment: 'Process Payment',
    paymentSuccessful: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    refund: 'Refund',
    releasePayment: 'Release Payment',
    
    // Notifications
    newBid: 'New Bid',
    jobUpdate: 'Job Update',
    messageReceived: 'Message Received',
    paymentReceived: 'Payment Received',
    appointmentReminder: 'Appointment Reminder',
    
    // Service Categories
    maintenance: 'Maintenance',
    repair: 'Repair',
    electrical: 'Electrical',
    detailing: 'Detailing',
    diagnostics: 'Diagnostics',
    oilChange: 'Oil Change',
    brakeService: 'Brake Service',
    engineRepair: 'Engine Repair',
    acRepair: 'AC Repair',
    transmission: 'Transmission',
    
    // Time and Date
    today: 'Today',
    tomorrow: 'Tomorrow',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    minutes: 'minutes',
    hours: 'hours',
    days: 'days',
    
    // Status
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    expired: 'Expired',
    active: 'Active',
    inactive: 'Inactive',
    
    // Actions
    view: 'View',
    share: 'Share',
    copy: 'Copy',
    paste: 'Paste',
    refresh: 'Refresh',
    reload: 'Reload',
    retry: 'Retry',
    skip: 'Skip',
    finish: 'Finish',
    start: 'Start',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
  },
  es: {
    // Common
    home: 'Inicio',
    explore: 'Explorar',
    messages: 'Mensajes',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    search: 'Buscar',
    filter: 'Filtrar',
    all: 'Todos',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    yes: 'Sí',
    no: 'No',
    ok: 'OK',
    back: 'Atrás',
    next: 'Siguiente',
    previous: 'Anterior',
    done: 'Hecho',
    close: 'Cerrar',
    open: 'Abrir',
    select: 'Seleccionar',
    submit: 'Enviar',
    confirm: 'Confirmar',
    continue: 'Continuar',
    
    // Navigation
    dashboard: 'Panel',
    jobs: 'Trabajos',
    findJobs: 'Buscar Trabajos',
    activeJobs: 'Trabajos Activos',
    jobHistory: 'Historial de Trabajos',
    bidding: 'Ofertas',
    myBookings: 'Mis Reservas',
    bookService: 'Reservar Servicio',
    
    // Home Screen
    goodMorning: '¡Buenos Días!',
    goodAfternoon: '¡Buenas Tardes!',
    goodEvening: '¡Buenas Noches!',
    beProductiveToday: '¡Sé Productivo Hoy!',
    quickActions: 'Acciones Rápidas',
    createJob: 'Crear Trabajo',
    postNewServiceRequest: 'Publicar una nueva solicitud de servicio',
    myJobs: 'Mis Trabajos',
    manageYourRequests: 'Gestiona tus solicitudes',
    chatWithMechanics: 'Chatea con mecánicos',
    carDetails: 'Detalles del Auto',
    manageYourVehicles: 'Gestiona tus vehículos',
    activeProjects: 'Proyectos Activos',
    viewAll: 'Ver Todo',
    scheduledServices: 'Servicios Programados',
    availableMechanics: 'Mecánicos Disponibles',
    
    // Explore Screen
    findPerfectMechanic: 'Encuentra el mecánico perfecto para tus necesidades',
    searchMechanicsOrSpecialties: 'Buscar mecánicos o especialidades...',
    categories: 'Categorías',
    languages: 'Idiomas',
    noMechanicsFound: 'No se encontraron mecánicos que coincidan con tus criterios',
    contact: 'Contactar',
    yearsExp: 'años exp.',
    languagesSpoken: 'Idiomas:',
    
    // Profile Screen
    customer: 'Cliente',
    mechanic: 'Mecánico',
    editProfile: 'Editar Perfil',
    preferences: 'Preferencias',
    notifications: 'Notificaciones',
    privacy: 'Privacidad',
    help: 'Ayuda',
    about: 'Acerca de',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Oscuro',
    userInfo: 'Información del Usuario',
    professionalStats: 'Estadísticas Profesionales',
    completedJobs: 'Trabajos Completados',
    totalJobs: 'Total de Trabajos',
    specialties: 'Especialidades',
    expertise: 'Experiencia',
    personalStatement: 'Declaración Personal',
    hourlyRate: 'Tarifa por Hora',
    
    // Auth
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    signUp: 'Registrarse',
    signIn: 'Iniciar Sesión',
    easyLogin: 'Inicio Rápido',
    customerLogin: 'Inicio de Cliente',
    mechanicLogin: 'Inicio de Mecánico',
    selectUserType: 'Seleccionar Tipo de Usuario',
    
    // Job related
    createNewJob: 'Crear Nuevo Trabajo',
    jobTitle: 'Título del Trabajo',
    jobDescription: 'Descripción del Trabajo',
    serviceType: 'Tipo de Servicio',
    urgency: 'Urgencia',
    low: 'Baja',
    medium: 'Media',
    high: 'Alta',
    estimatedDuration: 'Duración Estimada',
    budget: 'Presupuesto',
    location: 'Ubicación',
    carInformation: 'Información del Auto',
    addCarDetails: 'Agregar Detalles del Auto',
    helpMechanicsWithBetterDiagnostics: 'Ayuda a los mecánicos con mejores diagnósticos',
    jobManagement: 'Gestión de Trabajos',
    jobStatus: 'Estado del Trabajo',
    inProgress: 'En Progreso',
    completed: 'Completado',
    cancelled: 'Cancelado',
    requirements: 'Requisitos',
    acceptedBid: 'Oferta Aceptada',
    
    // Car Info
    carMake: 'Marca del Auto',
    carModel: 'Modelo del Auto',
    carYear: 'Año del Auto',
    carColor: 'Color del Auto',
    licensePlate: 'Placa de Matrícula',
    vinNumber: 'Número VIN',
    mileage: 'Kilometraje',
    lastServiceDate: 'Fecha del Último Servicio',
    serviceHistory: 'Historial de Servicios',
    vehicleDetails: 'Detalles del Vehículo',
    addVehicle: 'Agregar Vehículo',
    updateVehicle: 'Actualizar Vehículo',
    
    // Messaging
    sendMessage: 'Enviar Mensaje',
    typeMessage: 'Escribe un mensaje...',
    newMessage: 'Nuevo Mensaje',
    messageHistory: 'Historial de Mensajes',
    online: 'En Línea',
    offline: 'Desconectado',
    lastSeen: 'Visto por última vez',
    
    // Bidding
    submitBid: 'Enviar Oferta',
    bidAmount: 'Cantidad de la Oferta',
    estimatedTime: 'Tiempo Estimado',
    bidMessage: 'Mensaje',
    availableDate: 'Fecha Disponible',
    bidSubmitted: 'Oferta Enviada',
    bidAccepted: 'Oferta Aceptada',
    bidRejected: 'Oferta Rechazada',
    
    // Reviews
    rateMechanic: 'Calificar Mecánico',
    rateYourExperience: 'Califica tu Experiencia',
    overallRating: 'Calificación General',
    quality: 'Calidad',
    timeliness: 'Puntualidad',
    communication: 'Comunicación',
    cleanliness: 'Limpieza',
    writeReview: 'Escribir Reseña',
    submitReview: 'Enviar Reseña',
    reviewSubmitted: 'Reseña Enviada',
    
    // Scheduling
    scheduleAppointment: 'Programar Cita',
    selectDate: 'Seleccionar Fecha',
    selectTime: 'Seleccionar Hora',
    appointmentBooked: 'Cita Programada',
    reschedule: 'Reprogramar',
    cancelAppointment: 'Cancelar Cita',
    
    // Payment
    payment: 'Pago',
    paymentMethod: 'Método de Pago',
    cardNumber: 'Número de Tarjeta',
    expiryDate: 'Fecha de Vencimiento',
    cvv: 'CVV',
    cardholderName: 'Nombre del Titular',
    processPayment: 'Procesar Pago',
    paymentSuccessful: 'Pago Exitoso',
    paymentFailed: 'Pago Fallido',
    refund: 'Reembolso',
    releasePayment: 'Liberar Pago',
    
    // Notifications
    newBid: 'Nueva Oferta',
    jobUpdate: 'Actualización de Trabajo',
    messageReceived: 'Mensaje Recibido',
    paymentReceived: 'Pago Recibido',
    appointmentReminder: 'Recordatorio de Cita',
    
    // Service Categories
    maintenance: 'Mantenimiento',
    repair: 'Reparación',
    electrical: 'Eléctrico',
    detailing: 'Detallado',
    diagnostics: 'Diagnóstico',
    oilChange: 'Cambio de Aceite',
    brakeService: 'Servicio de Frenos',
    engineRepair: 'Reparación de Motor',
    acRepair: 'Reparación de Aire Acondicionado',
    transmission: 'Transmisión',
    
    // Time and Date
    today: 'Hoy',
    tomorrow: 'Mañana',
    yesterday: 'Ayer',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mes',
    minutes: 'minutos',
    hours: 'horas',
    days: 'días',
    
    // Status
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    expired: 'Expirado',
    active: 'Activo',
    inactive: 'Inactivo',
    
    // Actions
    view: 'Ver',
    share: 'Compartir',
    copy: 'Copiar',
    paste: 'Pegar',
    refresh: 'Actualizar',
    reload: 'Recargar',
    retry: 'Reintentar',
    skip: 'Omitir',
    finish: 'Terminar',
    start: 'Iniciar',
    stop: 'Detener',
    pause: 'Pausar',
    resume: 'Reanudar',
  },
  fr: {
    // Common
    home: 'Accueil',
    explore: 'Explorer',
    messages: 'Messages',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    search: 'Rechercher',
    filter: 'Filtrer',
    all: 'Tous',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    yes: 'Oui',
    no: 'Non',
    ok: 'OK',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    done: 'Terminé',
    close: 'Fermer',
    open: 'Ouvrir',
    select: 'Sélectionner',
    submit: 'Soumettre',
    confirm: 'Confirmer',
    continue: 'Continuer',
    
    // Navigation
    dashboard: 'Tableau de bord',
    jobs: 'Emplois',
    findJobs: 'Trouver des emplois',
    activeJobs: 'Emplois actifs',
    jobHistory: 'Historique des emplois',
    bidding: 'Enchères',
    myBookings: 'Mes réservations',
    bookService: 'Réserver un service',
    
    // Home Screen
    goodMorning: 'Bonjour!',
    goodAfternoon: 'Bon après-midi!',
    goodEvening: 'Bonsoir!',
    beProductiveToday: 'Soyez productif aujourd\'hui!',
    quickActions: 'Actions rapides',
    createJob: 'Créer un emploi',
    postNewServiceRequest: 'Publier une nouvelle demande de service',
    myJobs: 'Mes emplois',
    manageYourRequests: 'Gérez vos demandes',
    chatWithMechanics: 'Discuter avec les mécaniciens',
    carDetails: 'Détails de la voiture',
    manageYourVehicles: 'Gérez vos véhicules',
    activeProjects: 'Projets actifs',
    viewAll: 'Voir tout',
    scheduledServices: 'Services programmés',
    availableMechanics: 'Mécaniciens disponibles',
    
    // Explore Screen
    findPerfectMechanic: 'Trouvez le mécanicien parfait pour vos besoins',
    searchMechanicsOrSpecialties: 'Rechercher des mécaniciens ou spécialités...',
    categories: 'Catégories',
    languages: 'Langues',
    noMechanicsFound: 'Aucun mécanicien trouvé correspondant à vos critères',
    contact: 'Contacter',
    yearsExp: 'années d\'exp.',
    languagesSpoken: 'Langues parlées:',
    
    // Profile Screen
    customer: 'Client',
    mechanic: 'Mécanicien',
    editProfile: 'Modifier le profil',
    preferences: 'Préférences',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    help: 'Aide',
    about: 'À propos',
    language: 'Langue',
    theme: 'Thème',
    darkMode: 'Mode sombre',
    userInfo: 'Informations utilisateur',
    professionalStats: 'Statistiques professionnelles',
    completedJobs: 'Emplois terminés',
    totalJobs: 'Total des emplois',
    specialties: 'Spécialités',
    expertise: 'Expertise',
    personalStatement: 'Déclaration personnelle',
    hourlyRate: 'Taux horaire',
    
    // Auth
    login: 'Connexion',
    signup: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    forgotPassword: 'Mot de passe oublié?',
    rememberMe: 'Se souvenir de moi',
    loginWithGoogle: 'Se connecter avec Google',
    loginWithFacebook: 'Se connecter avec Facebook',
    dontHaveAccount: 'Vous n\'avez pas de compte?',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    createAccount: 'Créer un compte',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    welcomeBack: 'Bon retour!',
    welcomeToQueued: 'Bienvenue dans QueueUp',
    getStarted: 'Commencer',
    
    // Service Categories
    engineRepair: 'Réparation moteur',
    brakeService: 'Service de freinage',
    acRepair: 'Réparation climatisation',
    electrical: 'Électrique',
    transmission: 'Transmission',
    oilChange: 'Changement d\'huile',
    tireService: 'Service pneus',
    inspection: 'Inspection',
    
    // Job Status
    inProgress: 'En cours',
    completed: 'Terminé',
    cancelled: 'Annulé',
    pending: 'En attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    
    // Time
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
    yesterday: 'Hier',
    thisWeek: 'Cette semaine',
    nextWeek: 'Semaine prochaine',
    thisMonth: 'Ce mois',
    nextMonth: 'Mois prochain',
    
    // Actions
    book: 'Réserver',
    reschedule: 'Reprogrammer',
    rate: 'Évaluer',
    review: 'Avis',
    message: 'Message',
    call: 'Appeler',
    navigate: 'Naviguer',
    share: 'Partager',
    report: 'Signaler',
    block: 'Bloquer',
    unblock: 'Débloquer',
    favorite: 'Favori',
    unfavorite: 'Retirer des favoris',
    
    // Status
    online: 'En ligne',
    offline: 'Hors ligne',
    busy: 'Occupé',
    available: 'Disponible',
    away: 'Absent',
    
    // Payment
    payment: 'Paiement',
    price: 'Prix',
    total: 'Total',
    subtotal: 'Sous-total',
    tax: 'Taxe',
    tip: 'Pourboire',
    discount: 'Remise',
    coupon: 'Coupon',
    creditCard: 'Carte de crédit',
    debitCard: 'Carte de débit',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cash: 'Espèces',
    
    // Rating
    rating: 'Évaluation',
    stars: 'Étoiles',
    excellent: 'Excellent',
    good: 'Bon',
    average: 'Moyen',
    poor: 'Mauvais',
    terrible: 'Terrible',
    
    // Calendar
    calendar: 'Calendrier',
    date: 'Date',
    time: 'Heure',
    duration: 'Durée',
    appointment: 'Rendez-vous',
    schedule: 'Programmer',
    availability: 'Disponibilité',
    
    // Location
    location: 'Emplacement',
    address: 'Adresse',
    city: 'Ville',
    state: 'État',
    country: 'Pays',
    zipCode: 'Code postal',
    coordinates: 'Coordonnées',
    distance: 'Distance',
    nearby: 'À proximité',
    
    // Vehicle
    vehicle: 'Véhicule',
    make: 'Marque',
    model: 'Modèle',
    year: 'Année',
    color: 'Couleur',
    licensePlate: 'Plaque d\'immatriculation',
    vin: 'VIN',
    mileage: 'Kilométrage',
    
    // Communication
    chat: 'Chat',
    video: 'Vidéo',
    sms: 'SMS',
    notification: 'Notification',
    alert: 'Alerte',
    reminder: 'Rappel',
    
    // Settings
    general: 'Général',
    account: 'Compte',
    security: 'Sécurité',
    appearance: 'Apparence',
    region: 'Région',
    currency: 'Devise',
    units: 'Unités',
    
    // Error Messages
    somethingWentWrong: 'Quelque chose s\'est mal passé',
    networkError: 'Erreur réseau',
    serverError: 'Erreur serveur',
    notFound: 'Non trouvé',
    unauthorized: 'Non autorisé',
    forbidden: 'Interdit',
    validationError: 'Erreur de validation',
    timeout: 'Délai d\'attente dépassé',
    
    // Success Messages
    saved: 'Enregistré',
    updated: 'Mis à jour',
    deleted: 'Supprimé',
    created: 'Créé',
    sent: 'Envoyé',
    received: 'Reçu',
    
    // Confirmation
    areYouSure: 'Êtes-vous sûr?',
    areYouSureLogout: 'Êtes-vous sûr de vouloir vous déconnecter?',
    areYouSureDelete: 'Êtes-vous sûr de vouloir supprimer?',
    areYouSureCancel: 'Êtes-vous sûr de vouloir annuler?',
    
    // Media
    camera: 'Caméra',
    gallery: 'Galerie',
    photo: 'Photo',
    audio: 'Audio',
    document: 'Document',
    file: 'Fichier',
    upload: 'Télécharger',
    download: 'Télécharger',
    
    // Navigation
    forward: 'Avancer',
    refresh: 'Actualiser',
    reload: 'Recharger',
    stop: 'Arrêter',
    pause: 'Pause',
    resume: 'Reprendre',
  },
  de: {
    // Common
    home: 'Startseite',
    explore: 'Erkunden',
    messages: 'Nachrichten',
    profile: 'Profil',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    search: 'Suchen',
    filter: 'Filtern',
    all: 'Alle',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    yes: 'Ja',
    no: 'Nein',
    ok: 'OK',
    back: 'Zurück',
    next: 'Weiter',
    previous: 'Vorherige',
    done: 'Fertig',
    close: 'Schließen',
    open: 'Öffnen',
    select: 'Auswählen',
    submit: 'Absenden',
    confirm: 'Bestätigen',
    continue: 'Fortfahren',
    
    // Navigation
    dashboard: 'Dashboard',
    jobs: 'Jobs',
    findJobs: 'Jobs finden',
    activeJobs: 'Aktive Jobs',
    jobHistory: 'Job-Verlauf',
    bidding: 'Bieten',
    myBookings: 'Meine Buchungen',
    bookService: 'Service buchen',
    
    // Home Screen
    goodMorning: 'Guten Morgen!',
    goodAfternoon: 'Guten Tag!',
    goodEvening: 'Guten Abend!',
    beProductiveToday: 'Seien Sie heute produktiv!',
    quickActions: 'Schnellaktionen',
    createJob: 'Job erstellen',
    postNewServiceRequest: 'Neue Serviceanfrage veröffentlichen',
    myJobs: 'Meine Jobs',
    manageYourRequests: 'Verwalten Sie Ihre Anfragen',
    chatWithMechanics: 'Mit Mechanikern chatten',
    carDetails: 'Fahrzeugdetails',
    manageYourVehicles: 'Verwalten Sie Ihre Fahrzeuge',
    activeProjects: 'Aktive Projekte',
    viewAll: 'Alle anzeigen',
    scheduledServices: 'Geplante Services',
    availableMechanics: 'Verfügbare Mechaniker',
    
    // Explore Screen
    findPerfectMechanic: 'Finden Sie den perfekten Mechaniker für Ihre Bedürfnisse',
    searchMechanicsOrSpecialties: 'Mechaniker oder Spezialitäten suchen...',
    categories: 'Kategorien',
    languages: 'Sprachen',
    noMechanicsFound: 'Keine Mechaniker gefunden, die Ihren Kriterien entsprechen',
    contact: 'Kontakt',
    yearsExp: 'Jahre Erfahrung',
    languagesSpoken: 'Gesprochene Sprachen:',
    
    // Profile Screen
    customer: 'Kunde',
    mechanic: 'Mechaniker',
    editProfile: 'Profil bearbeiten',
    preferences: 'Einstellungen',
    notifications: 'Benachrichtigungen',
    privacy: 'Datenschutz',
    help: 'Hilfe',
    about: 'Über',
    language: 'Sprache',
    theme: 'Design',
    darkMode: 'Dunkler Modus',
    userInfo: 'Benutzerinformationen',
    professionalStats: 'Berufsstatistiken',
    completedJobs: 'Abgeschlossene Jobs',
    totalJobs: 'Gesamte Jobs',
    specialties: 'Spezialitäten',
    expertise: 'Expertise',
    personalStatement: 'Persönliche Aussage',
    hourlyRate: 'Stundensatz',
    
    // Auth
    login: 'Anmelden',
    signup: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    forgotPassword: 'Passwort vergessen?',
    rememberMe: 'Angemeldet bleiben',
    loginWithGoogle: 'Mit Google anmelden',
    loginWithFacebook: 'Mit Facebook anmelden',
    dontHaveAccount: 'Haben Sie noch kein Konto?',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    createAccount: 'Konto erstellen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    welcomeBack: 'Willkommen zurück!',
    welcomeToQueued: 'Willkommen bei QueueUp',
    getStarted: 'Loslegen',
    
    // Service Categories
    engineRepair: 'Motordreparatur',
    brakeService: 'Bremsenservice',
    acRepair: 'Klimaanlagenreparatur',
    electrical: 'Elektrik',
    transmission: 'Getriebe',
    oilChange: 'Ölwechsel',
    tireService: 'Reifenservice',
    inspection: 'Inspektion',
    
    // Job Status
    inProgress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    cancelled: 'Storniert',
    pending: 'Ausstehend',
    approved: 'Genehmigt',
    rejected: 'Abgelehnt',
    
    // Time
    today: 'Heute',
    tomorrow: 'Morgen',
    yesterday: 'Gestern',
    thisWeek: 'Diese Woche',
    nextWeek: 'Nächste Woche',
    thisMonth: 'Diesen Monat',
    nextMonth: 'Nächsten Monat',
    
    // Actions
    book: 'Buchen',
    reschedule: 'Neu terminieren',
    rate: 'Bewerten',
    review: 'Bewertung',
    message: 'Nachricht',
    call: 'Anrufen',
    navigate: 'Navigieren',
    share: 'Teilen',
    report: 'Melden',
    block: 'Blockieren',
    unblock: 'Entblockieren',
    favorite: 'Favorit',
    unfavorite: 'Aus Favoriten entfernen',
    
    // Status
    online: 'Online',
    offline: 'Offline',
    busy: 'Beschäftigt',
    available: 'Verfügbar',
    away: 'Abwesend',
    
    // Payment
    payment: 'Zahlung',
    price: 'Preis',
    total: 'Gesamt',
    subtotal: 'Zwischensumme',
    tax: 'Steuer',
    tip: 'Trinkgeld',
    discount: 'Rabatt',
    coupon: 'Gutschein',
    creditCard: 'Kreditkarte',
    debitCard: 'Debitkarte',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cash: 'Bargeld',
    
    // Rating
    rating: 'Bewertung',
    stars: 'Sterne',
    excellent: 'Ausgezeichnet',
    good: 'Gut',
    average: 'Durchschnittlich',
    poor: 'Schlecht',
    terrible: 'Schrecklich',
    
    // Calendar
    calendar: 'Kalender',
    date: 'Datum',
    time: 'Zeit',
    duration: 'Dauer',
    appointment: 'Termin',
    schedule: 'Planen',
    availability: 'Verfügbarkeit',
    
    // Location
    location: 'Standort',
    address: 'Adresse',
    city: 'Stadt',
    state: 'Bundesland',
    country: 'Land',
    zipCode: 'Postleitzahl',
    coordinates: 'Koordinaten',
    distance: 'Entfernung',
    nearby: 'In der Nähe',
    
    // Vehicle
    vehicle: 'Fahrzeug',
    make: 'Marke',
    model: 'Modell',
    year: 'Jahr',
    color: 'Farbe',
    licensePlate: 'Kennzeichen',
    vin: 'FIN',
    mileage: 'Kilometerstand',
    
    // Communication
    chat: 'Chat',
    video: 'Video',
    sms: 'SMS',
    notification: 'Benachrichtigung',
    alert: 'Warnung',
    reminder: 'Erinnerung',
    
    // Settings
    general: 'Allgemein',
    account: 'Konto',
    security: 'Sicherheit',
    appearance: 'Erscheinungsbild',
    region: 'Region',
    currency: 'Währung',
    units: 'Einheiten',
    
    // Error Messages
    somethingWentWrong: 'Etwas ist schief gelaufen',
    networkError: 'Netzwerkfehler',
    serverError: 'Serverfehler',
    notFound: 'Nicht gefunden',
    unauthorized: 'Nicht autorisiert',
    forbidden: 'Verboten',
    validationError: 'Validierungsfehler',
    timeout: 'Zeitüberschreitung',
    
    // Success Messages
    saved: 'Gespeichert',
    updated: 'Aktualisiert',
    deleted: 'Gelöscht',
    created: 'Erstellt',
    sent: 'Gesendet',
    received: 'Empfangen',
    
    // Confirmation
    areYouSure: 'Sind Sie sicher?',
    areYouSureLogout: 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    areYouSureDelete: 'Sind Sie sicher, dass Sie löschen möchten?',
    areYouSureCancel: 'Sind Sie sicher, dass Sie stornieren möchten?',
    
    // Media
    camera: 'Kamera',
    gallery: 'Galerie',
    photo: 'Foto',
    audio: 'Audio',
    document: 'Dokument',
    file: 'Datei',
    upload: 'Hochladen',
    download: 'Herunterladen',
    
    // Navigation
    forward: 'Vorwärts',
    refresh: 'Aktualisieren',
    reload: 'Neu laden',
    stop: 'Stoppen',
    pause: 'Pausieren',
    resume: 'Fortsetzen',
  },
  it: {
    // Common
    explore: 'Esplora',
    messages: 'Messaggi',
    profile: 'Profilo',
    settings: 'Impostazioni',
    logout: 'Disconnetti',
    save: 'Salva',
    cancel: 'Annulla',
    edit: 'Modifica',
    delete: 'Elimina',
    search: 'Cerca',
    filter: 'Filtra',
    all: 'Tutti',
    loading: 'Caricamento...',
    error: 'Errore',
    success: 'Successo',
    yes: 'Sì',
    no: 'No',
    ok: 'OK',
    back: 'Indietro',
    next: 'Avanti',
    previous: 'Precedente',
    done: 'Fatto',
    close: 'Chiudi',
    open: 'Apri',
    select: 'Seleziona',
    submit: 'Invia',
    confirm: 'Conferma',
    continue: 'Continua',
    
    // Navigation
    dashboard: 'Dashboard',
    jobs: 'Lavori',
    findJobs: 'Trova lavori',
    activeJobs: 'Lavori attivi',
    jobHistory: 'Cronologia lavori',
    bidding: 'Offerte',
    myBookings: 'Le mie prenotazioni',
    bookService: 'Prenota servizio',
    
    // Home Screen
    goodMorning: 'Buongiorno!',
    goodAfternoon: 'Buon pomeriggio!',
    goodEvening: 'Buonasera!',
    beProductiveToday: 'Sii produttivo oggi!',
    quickActions: 'Azioni rapide',
    createJob: 'Crea lavoro',
    postNewServiceRequest: 'Pubblica una nuova richiesta di servizio',
    myJobs: 'I miei lavori',
    manageYourRequests: 'Gestisci le tue richieste',
    chatWithMechanics: 'Chatta con i meccanici',
    carDetails: 'Dettagli auto',
    manageYourVehicles: 'Gestisci i tuoi veicoli',
    activeProjects: 'Progetti attivi',
    viewAll: 'Visualizza tutto',
    scheduledServices: 'Servizi programmati',
    availableMechanics: 'Meccanici disponibili',
    
    // Explore Screen
    findPerfectMechanic: 'Trova il meccanico perfetto per le tue esigenze',
    searchMechanicsOrSpecialties: 'Cerca meccanici o specialità...',
    categories: 'Categorie',
    languages: 'Lingue',
    noMechanicsFound: 'Nessun meccanico trovato che corrisponda ai tuoi criteri',
    contact: 'Contatta',
    yearsExp: 'anni di esperienza',
    languagesSpoken: 'Lingue parlate:',
    
    // Profile Screen
    customer: 'Cliente',
    mechanic: 'Meccanico',
    editProfile: 'Modifica profilo',
    preferences: 'Preferenze',
    notifications: 'Notifiche',
    privacy: 'Privacy',
    help: 'Aiuto',
    about: 'Informazioni',
    language: 'Lingua',
    theme: 'Tema',
    darkMode: 'Modalità scura',
    userInfo: 'Informazioni utente',
    professionalStats: 'Statistiche professionali',
    completedJobs: 'Lavori completati',
    totalJobs: 'Totale lavori',
    specialties: 'Specialità',
    expertise: 'Competenze',
    personalStatement: 'Dichiarazione personale',
    hourlyRate: 'Tariffa oraria',
    
    // Auth
    login: 'Accedi',
    signup: 'Registrati',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Conferma password',
    forgotPassword: 'Password dimenticata?',
    rememberMe: 'Ricordami',
    loginWithGoogle: 'Accedi con Google',
    loginWithFacebook: 'Accedi con Facebook',
    dontHaveAccount: 'Non hai un account?',
    alreadyHaveAccount: 'Hai già un account?',
    createAccount: 'Crea account',
    signIn: 'Accedi',
    signUp: 'Registrati',
    welcomeBack: 'Bentornato!',
    welcomeToQueued: 'Benvenuto in QueueUp',
    getStarted: 'Inizia',
    
    // Service Categories
    engineRepair: 'Riparazione motore',
    brakeService: 'Servizio freni',
    acRepair: 'Riparazione aria condizionata',
    electrical: 'Elettrico',
    transmission: 'Trasmissione',
    oilChange: 'Cambio olio',
    tireService: 'Servizio pneumatici',
    inspection: 'Ispezione',
    
    // Job Status
    inProgress: 'In corso',
    completed: 'Completato',
    cancelled: 'Annullato',
    pending: 'In attesa',
    approved: 'Approvato',
    rejected: 'Rifiutato',
    
    // Time
    today: 'Oggi',
    tomorrow: 'Domani',
    yesterday: 'Ieri',
    thisWeek: 'Questa settimana',
    nextWeek: 'Prossima settimana',
    thisMonth: 'Questo mese',
    nextMonth: 'Prossimo mese',
    
    // Actions
    book: 'Prenota',
    reschedule: 'Riprogramma',
    rate: 'Valuta',
    review: 'Recensione',
    message: 'Messaggio',
    call: 'Chiama',
    navigate: 'Naviga',
    share: 'Condividi',
    report: 'Segnala',
    block: 'Blocca',
    unblock: 'Sblocca',
    favorite: 'Preferito',
    unfavorite: 'Rimuovi dai preferiti',
    
    // Status
    online: 'Online',
    offline: 'Offline',
    busy: 'Occupato',
    available: 'Disponibile',
    away: 'Assente',
    
    // Payment
    payment: 'Pagamento',
    price: 'Prezzo',
    total: 'Totale',
    subtotal: 'Subtotale',
    tax: 'Tassa',
    tip: 'Mancia',
    discount: 'Sconto',
    coupon: 'Coupon',
    creditCard: 'Carta di credito',
    debitCard: 'Carta di debito',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cash: 'Contanti',
    
    // Rating
    rating: 'Valutazione',
    stars: 'Stelle',
    excellent: 'Eccellente',
    good: 'Buono',
    average: 'Medio',
    poor: 'Scarso',
    terrible: 'Terribile',
    
    // Calendar
    calendar: 'Calendario',
    date: 'Data',
    time: 'Ora',
    duration: 'Durata',
    appointment: 'Appuntamento',
    schedule: 'Programma',
    availability: 'Disponibilità',
    
    // Location
    location: 'Posizione',
    address: 'Indirizzo',
    city: 'Città',
    state: 'Stato',
    country: 'Paese',
    zipCode: 'Codice postale',
    coordinates: 'Coordinate',
    distance: 'Distanza',
    nearby: 'Nelle vicinanze',
    
    // Vehicle
    vehicle: 'Veicolo',
    make: 'Marca',
    model: 'Modello',
    year: 'Anno',
    color: 'Colore',
    licensePlate: 'Targa',
    vin: 'Telaio',
    mileage: 'Chilometraggio',
    
    // Communication
    chat: 'Chat',
    video: 'Video',
    sms: 'SMS',
    notification: 'Notifica',
    alert: 'Avviso',
    reminder: 'Promemoria',
    
    // Settings
    general: 'Generale',
    account: 'Account',
    security: 'Sicurezza',
    appearance: 'Aspetto',
    region: 'Regione',
    currency: 'Valuta',
    units: 'Unità',
    
    // Error Messages
    somethingWentWrong: 'Qualcosa è andato storto',
    networkError: 'Errore di rete',
    serverError: 'Errore del server',
    notFound: 'Non trovato',
    unauthorized: 'Non autorizzato',
    forbidden: 'Vietato',
    validationError: 'Errore di validazione',
    timeout: 'Timeout',
    
    // Success Messages
    saved: 'Salvato',
    updated: 'Aggiornato',
    deleted: 'Eliminato',
    created: 'Creato',
    sent: 'Inviato',
    received: 'Ricevuto',
    
    // Confirmation
    areYouSure: 'Sei sicuro?',
    areYouSureLogout: 'Sei sicuro di voler disconnetterti?',
    areYouSureDelete: 'Sei sicuro di voler eliminare?',
    areYouSureCancel: 'Sei sicuro di voler annullare?',
    
    // Media
    camera: 'Fotocamera',
    gallery: 'Galleria',
    photo: 'Foto',
    audio: 'Audio',
    document: 'Documento',
    file: 'File',
    upload: 'Carica',
    download: 'Scarica',
    
    // Navigation
    home: 'Home',
    forward: 'Avanti',
    refresh: 'Aggiorna',
    reload: 'Ricarica',
    stop: 'Ferma',
    pause: 'Pausa',
    resume: 'Riprendi',
  },
  pt: {
    // Common
    home: 'Início',
    explore: 'Explorar',
    messages: 'Mensagens',
    profile: 'Perfil',
    settings: 'Configurações',
    logout: 'Sair',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    search: 'Pesquisar',
    filter: 'Filtrar',
    all: 'Todos',
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    yes: 'Sim',
    no: 'Não',
    ok: 'OK',
    back: 'Voltar',
    next: 'Próximo',
    previous: 'Anterior',
    done: 'Concluído',
    close: 'Fechar',
    open: 'Abrir',
    select: 'Selecionar',
    submit: 'Enviar',
    confirm: 'Confirmar',
    continue: 'Continuar',
    
    // Navigation
    dashboard: 'Painel',
    jobs: 'Trabalhos',
    findJobs: 'Encontrar trabalhos',
    activeJobs: 'Trabalhos ativos',
    jobHistory: 'Histórico de trabalhos',
    bidding: 'Lances',
    myBookings: 'Minhas reservas',
    bookService: 'Reservar serviço',
    
    // Home Screen
    goodMorning: 'Bom dia!',
    goodAfternoon: 'Boa tarde!',
    goodEvening: 'Boa noite!',
    beProductiveToday: 'Seja produtivo hoje!',
    quickActions: 'Ações rápidas',
    createJob: 'Criar trabalho',
    postNewServiceRequest: 'Publicar nova solicitação de serviço',
    myJobs: 'Meus trabalhos',
    manageYourRequests: 'Gerencie suas solicitações',
    chatWithMechanics: 'Conversar com mecânicos',
    carDetails: 'Detalhes do carro',
    manageYourVehicles: 'Gerencie seus veículos',
    activeProjects: 'Projetos ativos',
    viewAll: 'Ver tudo',
    scheduledServices: 'Serviços agendados',
    availableMechanics: 'Mecânicos disponíveis',
    
    // Explore Screen
    findPerfectMechanic: 'Encontre o mecânico perfeito para suas necessidades',
    searchMechanicsOrSpecialties: 'Pesquisar mecânicos ou especialidades...',
    categories: 'Categorias',
    languages: 'Idiomas',
    noMechanicsFound: 'Nenhum mecânico encontrado que corresponda aos seus critérios',
    contact: 'Contato',
    yearsExp: 'anos de experiência',
    languagesSpoken: 'Idiomas falados:',
    
    // Profile Screen
    customer: 'Cliente',
    mechanic: 'Mecânico',
    editProfile: 'Editar perfil',
    preferences: 'Preferências',
    notifications: 'Notificações',
    privacy: 'Privacidade',
    help: 'Ajuda',
    about: 'Sobre',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo escuro',
    userInfo: 'Informações do usuário',
    professionalStats: 'Estatísticas profissionais',
    completedJobs: 'Trabalhos concluídos',
    totalJobs: 'Total de trabalhos',
    specialties: 'Especialidades',
    expertise: 'Experiência',
    personalStatement: 'Declaração pessoal',
    hourlyRate: 'Taxa horária',
    
    // Auth
    login: 'Entrar',
    signup: 'Cadastrar',
    email: 'Email',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    forgotPassword: 'Esqueceu a senha?',
    rememberMe: 'Lembrar de mim',
    loginWithGoogle: 'Entrar com Google',
    loginWithFacebook: 'Entrar com Facebook',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
    createAccount: 'Criar conta',
    signIn: 'Entrar',
    signUp: 'Cadastrar',
    welcomeBack: 'Bem-vindo de volta!',
    welcomeToQueued: 'Bem-vindo ao QueueUp',
    getStarted: 'Começar',
    
    // Service Categories
    engineRepair: 'Reparo do motor',
    brakeService: 'Serviço de freios',
    acRepair: 'Reparo do ar condicionado',
    electrical: 'Elétrico',
    transmission: 'Transmissão',
    oilChange: 'Troca de óleo',
    tireService: 'Serviço de pneus',
    inspection: 'Inspeção',
    
    // Job Status
    inProgress: 'Em andamento',
    completed: 'Concluído',
    cancelled: 'Cancelado',
    pending: 'Pendente',
    approved: 'Aprovado',
    rejected: 'Rejeitado',
    
    // Time
    today: 'Hoje',
    tomorrow: 'Amanhã',
    yesterday: 'Ontem',
    thisWeek: 'Esta semana',
    nextWeek: 'Próxima semana',
    thisMonth: 'Este mês',
    nextMonth: 'Próximo mês',
    
    // Actions
    book: 'Reservar',
    reschedule: 'Reagendar',
    rate: 'Avaliar',
    review: 'Avaliação',
    message: 'Mensagem',
    call: 'Ligar',
    navigate: 'Navegar',
    share: 'Compartilhar',
    report: 'Denunciar',
    block: 'Bloquear',
    unblock: 'Desbloquear',
    favorite: 'Favorito',
    unfavorite: 'Remover dos favoritos',
    
    // Status
    online: 'Online',
    offline: 'Offline',
    busy: 'Ocupado',
    available: 'Disponível',
    away: 'Ausente',
    
    // Payment
    payment: 'Pagamento',
    price: 'Preço',
    total: 'Total',
    subtotal: 'Subtotal',
    tax: 'Imposto',
    tip: 'Gorjeta',
    discount: 'Desconto',
    coupon: 'Cupom',
    creditCard: 'Cartão de crédito',
    debitCard: 'Cartão de débito',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cash: 'Dinheiro',
    
    // Rating
    rating: 'Avaliação',
    stars: 'Estrelas',
    excellent: 'Excelente',
    good: 'Bom',
    average: 'Médio',
    poor: 'Ruim',
    terrible: 'Terrível',
    
    // Calendar
    calendar: 'Calendário',
    date: 'Data',
    time: 'Hora',
    duration: 'Duração',
    appointment: 'Compromisso',
    schedule: 'Agendar',
    availability: 'Disponibilidade',
    
    // Location
    location: 'Localização',
    address: 'Endereço',
    city: 'Cidade',
    state: 'Estado',
    country: 'País',
    zipCode: 'CEP',
    coordinates: 'Coordenadas',
    distance: 'Distância',
    nearby: 'Próximo',
    
    // Vehicle
    vehicle: 'Veículo',
    make: 'Marca',
    model: 'Modelo',
    year: 'Ano',
    color: 'Cor',
    licensePlate: 'Placa',
    vin: 'Chassi',
    mileage: 'Quilometragem',
    
    // Communication
    chat: 'Chat',
    video: 'Vídeo',
    sms: 'SMS',
    notification: 'Notificação',
    alert: 'Alerta',
    reminder: 'Lembrete',
    
    // Settings
    general: 'Geral',
    account: 'Conta',
    security: 'Segurança',
    appearance: 'Aparência',
    region: 'Região',
    currency: 'Moeda',
    units: 'Unidades',
    
    // Error Messages
    somethingWentWrong: 'Algo deu errado',
    networkError: 'Erro de rede',
    serverError: 'Erro do servidor',
    notFound: 'Não encontrado',
    unauthorized: 'Não autorizado',
    forbidden: 'Proibido',
    validationError: 'Erro de validação',
    timeout: 'Timeout',
    
    // Success Messages
    saved: 'Salvo',
    updated: 'Atualizado',
    deleted: 'Excluído',
    created: 'Criado',
    sent: 'Enviado',
    received: 'Recebido',
    
    // Confirmation
    areYouSure: 'Tem certeza?',
    areYouSureLogout: 'Tem certeza de que deseja sair?',
    areYouSureDelete: 'Tem certeza de que deseja excluir?',
    areYouSureCancel: 'Tem certeza de que deseja cancelar?',
    
    // Media
    camera: 'Câmera',
    gallery: 'Galeria',
    photo: 'Foto',
    audio: 'Áudio',
    document: 'Documento',
    file: 'Arquivo',
    upload: 'Carregar',
    download: 'Baixar',
    
    // Navigation
    forward: 'Avançar',
    refresh: 'Atualizar',
    reload: 'Recarregar',
    stop: 'Parar',
    pause: 'Pausar',
    resume: 'Retomar',
  },
  // Add more languages as needed...
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      // Language is now managed in memory only - use default English
      setCurrentLanguage('en');
    } catch (error) {
      console.error('Error loading language:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const changeLanguage = async (languageCode) => {
    try {
      if (LANGUAGES[languageCode]) {
        setCurrentLanguage(languageCode);
        // Language is now managed in memory only
      }
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key) => {
    return TRANSLATIONS[currentLanguage]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const getAvailableLanguages = () => {
    return Object.values(LANGUAGES);
  };

  const getCurrentLanguageInfo = () => {
    return LANGUAGES[currentLanguage];
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    getAvailableLanguages,
    getCurrentLanguageInfo,
    isLoading,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
